'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const {
  COMMAND_LANGUAGES,
  detectCommandLanguage,
  extractCommandData,
} = require('../command-language');

const EPL_FROM_MAHIS = [
  'N',
  'q600',
  'Q230,20',
  'R130,0',
  'ZT',
  'S1',
  'A100,6,0,3,1,1,N,"Test ddddfff (M)"',
  'B100,30,0,1,3,8,80,N,"XAPP267M7"',
  'A100,118,0,3,1,1,N,"XAPP267M7   P1001"',
  'P1',
].join('\n');

test('detects the EPL format currently generated by MAHIS', () => {
  const result = detectCommandLanguage(EPL_FROM_MAHIS);
  assert.equal(result.language, COMMAND_LANGUAGES.EPL);
  assert.equal(result.confidence, 'high');
  assert.ok(result.indicators.includes('A text'));
  assert.ok(result.indicators.includes('P print'));
});

test('detects ZPL formats by their caret commands rather than field name', () => {
  const result = detectCommandLanguage(
    '\uFEFF ^XA^PW812^LL305^FO10,5^A0N,30,30^FDTEST^FS^XZ ',
  );
  assert.equal(result.language, COMMAND_LANGUAGES.ZPL);
  assert.equal(result.confidence, 'high');
});

test('reports unknown data instead of guessing a printer language', () => {
  assert.equal(
    detectCommandLanguage('SIZE 101.6 mm,38.1 mm\nCLS\nPRINT 1,1').language,
    COMMAND_LANGUAGES.UNKNOWN,
  );
  assert.equal(
    detectCommandLanguage('ordinary text to print').language,
    COMMAND_LANGUAGES.UNKNOWN,
  );
});

test('accepts legacy and language-neutral request field names', () => {
  assert.equal(extractCommandData({ zpl: EPL_FROM_MAHIS }), EPL_FROM_MAHIS);
  assert.equal(extractCommandData({ epl: EPL_FROM_MAHIS }), EPL_FROM_MAHIS);
  assert.equal(extractCommandData({ commands: 'commands-value' }), 'commands-value');
  assert.equal(extractCommandData({ data: 'data-value' }), 'data-value');
  assert.throws(() => extractCommandData({}), /Print commands are required/);
});
