#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  if [ -d /run/systemd/system ]; then
    systemctl disable zpl.service || true
    systemctl daemon-reload || true
  fi
fi

# On purge, drop the config directory too.
if [ "$1" = "purge" ]; then
  rm -rf /etc/zplexpress
fi

exit 0
